server:
    port: 8000
cnj:
   info:
       message: Server verwendet Configurattion aus Codebase!
spring:
    h2:
        console:
            enabled: true
    datasource:
        url2: test
        url: ${JDBC_DATABASE_URL:}
        hikari:
            connection-timeout:30000
            maximum-pool-size:2