server:
    port: 8000
cnj:
   info:
       message: Server verwendet Configurattion aus Codebase!
spring:
    h2:
        console:
            enabled: true
    datasource:
        url: ${JDBC_DATABASE_URL:}
        hikari:
            connection-timeout:30000
            maximum-pool-size:2
            driverClassName:org.postgresql.Driver
            maxActive:10
            maxIdle:5
            minIdle:2
            initialSize:5
            removeAbandoned:true